package fes.aragon.token;

public enum TokensMike {
    INICIO, FIN, ENTERO, REAL, MIENTRAS, FINMIENTRAS, SI, SINO,
    ASIGNACION, PUNTO_COMA, COMA, PARENTESIS_A, PARENTESIS_C,
    OPERADOR_ARITMETICO, COMPARACION, IDENTIFICADOR, NUMERO, ERROR
}